#!/bin/bash

python ../atlas_kafka_event_listener/main.py "$ATLAS_HOSTNAME" "$ATLAS_PORT" "$KAFKA_BROKER_URL" "$KAFKA_TOPIC_NAME" "$CONSUMER_GROUP_ID" "$KC_URL" "$REALM_NAME" "$CLIENT_ID" "$CLIENT_SECRET"


# python main.py "$ATLAS_HOSTNAME" "$ATLAS_PORT" "$KAFKA_BROKER_URL" "$KAFKA_TOPIC_NAME" "$CONSUMER_GROUP_ID" "$KC_URL" "$REALM_NAME" "$CLIENT_ID" "$CLIENT_SECRET"